# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c44c9e76208a585d912bc12f6ffb4aeb1ec21dac410986307058716ed62d9f99122576771b389f51c6216e4e16d9110b9f193ac8aac09eae850a5ed26ace50

test:
  secret_key_base: 70e4415ea1f257908679866f371cb59313a66c301f02b1f8622a1a273b51c96e1654eec1f29bfc78d95dc12441057cf6538b3fffd8424d120caea80d17f2fcb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
